version: '3.8'

networks:
  dev:

volumes:
  db-data:

services:

  # db:
  #   image: mysql:latest
  #   container_name: db
  #   restart: always
  #   volumes:
  #     - db-data:/var/lib/mysql
      
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #     MYSQL_DATABASE: ecommerce
  #     MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
  #   networks:
  #     - dev

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: phpmyadmin_safe
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: db
  #   networks:
  #     - dev

  symfony-api:
    build:
      context: .
      dockerfile: ecommerce/Dockerfile.symfony
    ports:
      - 8000:80
    networks:
      - dev
